name: medintel_pipeline
version: '1.0'
profile: medintel_pipeline

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analysis"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/data"]
macro-paths: ["dbt/macros"]

clean-targets: ["dbt/target"]
