version: '3.9'

services:
  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagster
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api  # optional: separate Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: medintel
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
